config {
  type: "table",
  schema: "fire_inc_gold",
  tags: ["47"],
  description: "Average response time per day, using silver fact table and dim_time for date analysis."
}

SELECT
  d.date,
  AVG(TIMESTAMP_DIFF(f.arrival_dttm, f.alarm_dttm, SECOND)) AS avg_response_seconds
FROM
  ${ref("fire_incident_with_year")} f
JOIN
  ${ref("dim_time")} d
  ON DATE(f.incident_date) = d.date
WHERE
  f.arrival_dttm IS NOT NULL AND f.alarm_dttm IS NOT NULL
GROUP BY
  d.date;